Ext.define('DndCharacterManager.view.SkillsModel', {
    extend: 'Ext.app.ViewModel',
    requires: ['DndCharacterManager.util.Common'],
    data: {
        proficiency: 2,
        strength: 10,
        dexterity: 10,
        constitution: 10,
        intelligence: 10,
        wisdom: 10,
        charisma: 10,

        acrobatics: false,
        acrobaticsExpertise: false,
        animalHandling: false,
        animalHandlingExpertise: false,
        arcana: false,
        arcanaExpertise: false,
        athletics: false,
        athleticsExpertise: false,
        deception: false,
        deceptionExpertise: false,
        history: false,
        historyExpertise: false,
        insight: false,
        insightExpertise: false,
        intimidation: false,
        intimidationExpertise: false,
        investigation: false,
        investigationExpertise: false,
        medicine: false,
        medicineExpertise: false,
        nature: false,
        perception: false,
        perceptionExpertise: false,
        performance: false,
        performanceExpertise: false,
        persuasion: false,
        persuasionExpertise: false,
        religion: false,
        religionExpertise: false,
        sleightOfHand: false,
        sleightOfHandExpertise: false,
        stealth: false,
        stealthExpertise: false,
        survival: false,
        survivalExpertise: false,
    },
    formulas: {
        strengthMod: (get) => Common.getModifier(get('strength')),
        dexterityMod: (get) => Common.getModifier(get('dexterity')),
        constitutionMod: (get) => Common.getModifier(get('constitution')),
        intelligenceMod: (get) => Common.getModifier(get('intelligence')),
        wisdomMod: (get) => Common.getModifier(get('wisdom')),
        charismaMod: (get) => Common.getModifier(get('charisma')),
    },
});
