Ext.define('DndCharacterManager.view.Skills', {
    extend: 'Ext.Panel',
    requires: ['DndCharacterManager.view.SkilField'],

    xtype: 'skills',

    title: 'Skills',

    items: [
        {
            xtype: 'skillfield',
            fieldLabel: 'Acrobatics',
            bind: {
                proficient: '{acrobatics}',
                expertise: '{acrobaticsExpertise}',
                modifier: '{dexterityMod}',
                proficiencyModifier: '{proficiency}',
            },
        },
        {
            xtype: 'skillfield',
            fieldLabel: 'Animal Handling',
            bind: {
                proficient: '{animalHandling}',
                expertise: '{animalHandlingExpertise}',
                modifier: '{wisdomMod}',
                proficiencyModifier: '{proficiency}',
            },
        },
        {
            xtype: 'skillfield',
            fieldLabel: 'Arcana',
            bind: {
                proficient: '{arcana}',
                expertise: '{arcanaExpertise}',
                modifier: '{intelligenceMod}',
                proficiencyModifier: '{proficiency}',
            },
        },
        {
            xtype: 'skillfield',
            fieldLabel: 'Athletics',
            bind: {
                proficient: '{athletics}',
                expertise: '{athleticsExpertise}',
                modifier: '{strengthMod}',
                proficiencyModifier: '{proficiency}',
            },
        },
        {
            xtype: 'skillfield',
            fieldLabel: 'Deception',
            bind: {
                proficient: '{deception}',
                expertise: '{deceptionExpertise}',
                modifier: '{charismaMod}',
                proficiencyModifier: '{proficiency}',
            },
        },
        {
            xtype: 'skillfield',
            fieldLabel: 'history',
            bind: {
                proficient: '{history}',
                expertise: '{historyExpertise}',
                modifier: '{intelligenceMod}',
                proficiencyModifier: '{proficiency}',
            },
        },
        {
            xtype: 'skillfield',
            fieldLabel: 'Insight',
            bind: {
                proficient: '{insight}',
                expertise: '{insightExpertise}',
                modifier: '{wisdomMod}',
                proficiencyModifier: '{proficiency}',
            },
        },
        {
            xtype: 'skillfield',
            fieldLabel: 'intimidation',
            bind: {
                proficient: '{intimidation}',
                expertise: '{intimidationExpertise}',
                modifier: '{charismaMod}',
                proficiencyModifier: '{proficiency}',
            },
        },
        {
            xtype: 'skillfield',
            fieldLabel: 'Investigation',
            bind: {
                proficient: '{investigation}',
                expertise: '{investigationExpertise}',
                modifier: '{intelligenceMod}',
                proficiencyModifier: '{proficiency}',
            },
        },
        {
            xtype: 'skillfield',
            fieldLabel: 'Medicine',
            bind: {
                proficient: '{medicine}',
                expertise: '{medicineExpertise}',
                modifier: '{wisdomMod}',
                proficiencyModifier: '{proficiency}',
            },
        },
        {
            xtype: 'skillfield',
            fieldLabel: 'Nature',
            bind: {
                proficient: '{nature}',
                expertise: '{natureExpertise}',
                modifier: '{intelligenceMod}',
                proficiencyModifier: '{proficiency}',
            },
        },
        {
            xtype: 'skillfield',
            fieldLabel: 'Perception',
            bind: {
                proficient: '{perception}',
                expertise: '{perceptionExpertise}',
                modifier: '{wisdomMod}',
            },
        },
        {
            xtype: 'skillfield',
            fieldLabel: 'Performance',
            bind: {
                proficient: '{performance}',
                expertise: '{performanceExpertise}',
                modifier: '{charismaMod}',
            },
        },
        {
            xtype: 'skillfield',
            fieldLabel: 'Persuasion',
            bind: {
                proficient: '{persuasion}',
                expertise: '{persuasionExpertise}',
                modifier: '{charismaMod}',
            },
        },
        {
            xtype: 'skillfield',
            fieldLabel: 'Religion',
            bind: {
                proficient: '{religion}',
                expertise: '{religionExpertise}',
                modifier: '{intelligenceMod}',
            },
        },
        {
            xtype: 'skillfield',
            fieldLabel: 'sleightOfHand',
            bind: {
                proficient: '{sleightOfHand}',
                expertise: '{sleightOfHandExpertise}',
                modifier: '{dexterityMod}',
            },
        },
        {
            xtype: 'skillfield',
            fieldLabel: 'Stealth',
            bind: {
                proficient: '{stealth}',
                expertise: '{stealthExpertise}',
                modifier: '{dexterityMod}',
                proficiencyModifier: '{proficiency}',
            },
        },
        {
            xtype: 'skillfield',
            fieldLabel: 'Survival',
            bind: {
                proficient: '{survival}',
                expertise: '{survivalExpertise}',
                abilityModifier: '{wisdomMod}',
                proficiencyModifier: '{proficiency}',
            },
        },
    ],
    config: {
        proficiency: 2,
        strength: 10,
        dexterity: 10,
        constitution: 10,
        intelligence: 10,
        wisdom: 10,
        charisma: 10,

        acrobatics: 0,
        animalHandling: 0,
        arcana: 0,
        athletics: 0,
        deception: 0,
        history: 0,
        insight: 0,
        intimidation: 0,
        investigation: 0,
        medicine: 0,
        nature: 0,
        perception: 0,
        performance: 0,
        persuasion: 0,
        religion: 0,
        sleightOfHand: 0,
        stealth: 0,
        survival: 0,
    },
    bind: {
        proficiency: '{proficiency}',
        strength: '{strength}',
        dexterity: '{dexterity}',
        constitution: '{constitution}',
        intelligence: '{intelligence}',
        wisdom: '{wisdom}',
        charisma: '{charisma}',
    },
    getSkill: (name) => {
        let vm = this.getViewModel(),
            data = vm.getData();
        if (data[name + 'Expertise']) {
            return 2;
        } else if (data[name]) {
            return 1;
        }
        return 0;
    },
    setSkill: (name, value) => {
        let vm = this.getViewModel(),
            proficient = value >= 1,
            expertise = value === 2,
            data = {};
        data[name] = proficient;
        data[name + 'Expertise'] = expertise;
        vm.setData(data);
    },
    publishes: [
        'proficiency',
        'strength',
        'dexterity',
        'constitution',
        'intelligence',
        'wisdom',
        'charisma',

        'acrobatics',
        'animalHandling',
        'arcana',
        'athletics',
        'deception',
        'history',
        'insight',
        'intimidation',
        'investigation',
        'medicine',
        'nature',
        'perception',
        'performance',
        'persuasion',
        'religion',
        'sleightOfHand',
        'stealth',
        'survival',
    ],
    getAcrobatics: () => this.getSkill('acrobatics'),
    setAcrobatics: (value) => this.setSkill('acrobatics', value),
    getAcrobatics: () => this.getSkill('animalHandling'),
    setAnimalHandling: (value) => this.setSkill('animalHandling', value),
    getArcana: () => this.getSkill('arcana'),
    setArcana: (value) => this.setSkill('arcana', value),
    getAthletics: () => this.setSkill('athletics'),
    setAthletics: (value) => this.setSkill('athletics', value),
    getDeception: () => this.getSkill('deception'),
    setDeception: (value) => this.setSkill('deception', value),
    getHistory: () => this.getSkill('history'),
    setHistory: (value) => this.setSkill('history', value),
    getInsight: () => this.getSkill('insight'),
    setInsight: (value) => this.setSkill('insight', value),
    getIntimidation: () => this.getSkill('intimidation'),
    setIntimidation: (value) => this.setSkill('intimidation', value),
    getInvestigation: () => this.getSkill('investigation'),
    setInvestigation: (value) => this.setSkill('investigation', value),
    getMedicine: () => this.getSkill('medicine'),
    setMedicine: (value) => this.setSkill('medicine', value),
    getNature: () => this.getSkill('nature'),
    setNature: (value) => this.setSkill('nature', value),
    getPerception: () => this.getSkill('perception'),
    setPerception: (value) => this.setSkill('perception', value),
    getPerformance: () => this.getSkill('performance'),
    setPerformance: (value) => this.setSkill('performance', value),
    getPersuasion: () => this.getSkill('persuasion'),
    setPersuasion: (value) => this.setSkill('persuasion', value),
    getReligion: () => this.getSkill('religion'),
    setReligion: (value) => this.setSkill('religion', value),
    getSleightOfHand: () => this.getSkill('sleightOfHand'),
    setSleightOfHand: (value) => this.setSkill('sleightOfHand', value),
    getStealth: () => this.getSkill('stealth'),
    setStealth: (value) => this.setSkill('stealth', value),
    getSurvival: () => this.getSkill('survival'),
    setSurvival: (value) => this.setSkill('survival', value),
});
